- hosts: webserver
  become: yes

  tasks:
    - name: Stop MySQL Docker container
      community.docker.docker_container:
        name: "{{ mysql_container_name }}"
        state: absent

    - name: Stop PHP-FPM Docker container
      community.docker.docker_container:
        name: "{{ php_fpm_container_name }}"
        state: absent

    - name: Stop NGINX Docker container
      community.docker.docker_container:
        name: "{{ nginx_container_name }}"
        state: absent
